### ISSUE TITLE
'No such directory' when adding new project

### ISSUE THREAD

**Issue by joelis10** [Maker-Management-Platform/docs#25]
![image](https://github.com/Maker-Management-Platform/docs/assets/9698210/c6df1fa3-7948-4c12-98ce-a910af1af479)

I'm trying to use this on a Synology NAS and feel as if the containers don't have the correct permissions to create a directory, since there are no specified UIDs. I've tried manually setting the permissions for 'Everyone' in the Synology DSM so that it should now have sufficient permissions to create a directory but it still throws the error

**Comment by joelis10** [comment]
![image](https://github.com/Maker-Management-Platform/docs/assets/9698210/a4da7746-bf93-4f85-a671-d371fe167376)
here's my docker compose

![image](https://github.com/Maker-Management-Platform/docs/assets/9698210/642e6fc2-c329-47ca-bbc1-23a0cbc9874b)
and here's the folder structure on my NAS. I had to create the config.toml file manually after installation failed so I feel like I've already done something wrong (especially since the toml file is empty even after setup).

**Comment by EduardoOliveira** [comment]
Hi there, sorry for the late reply. I've changed a lot of how the mount points work in v1.1.0, could you see if it still happens?

**Comment by joelis10** [comment]
thanks for the update, UI seems to work perfectly so far so thanks again

**Comment by EduardoOliveira** [comment]
I'll close the issue, please feel free to reach out if something happens

**Comment by joelis10** [comment]
You can keep this issue as closed and I'll open another if it helps, but is there any support currently for USB printers or is that on the roadmap?

**Comment by EduardoOliveira** [comment]
Please open another one, or join us on discord for a discussion :)
