### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by kireol** [Maker-Management-Platform/docs#26]
Running this in docker.  Anything I do in the web UI, except for changing the theme results in a 502 message.

This was showing up in my log.

	{"level":"error","ts":1706918632.860387,"logger":"http.log.error","msg":"dial tcp: lookup agent on 127.0.0.11:53: no such host","request":{"remote_addr":"172.31.0.1:54740","proto":"HTTP/1.1","method":"GET","host":"192.168.1.170:8081","uri":"/api/printers?_=1972","headers":{"Cookie":["did=y8vJObUJ5JpHGKpnuINKXObbXSWeBOgryXv1xFSpA4TrNTHv41obCsBNhm57pYjqkEytYHu2LiKn5h7hsMZ9eA; _SSID=YES4MiK3UCbTMcvI672tRmkioi3uXpZcrFF3LWZLdwU; _CrPoSt=cHJvdG9jb2w9aHR0cDo7IHBvcnQ9NTAwMDsgcGF0aG5hbWU9Lzs%3D; stay_login=1; id=WKDImozJgAfX6b2igWv_jZagV_2X6_Vc0whDJo-rpb8p91UcLUts09mk2O8ALVeyqpmrCH5QceUuYH0D78tIts; ProwlarrAuth=CfDJ8H3EB-1NXTNDu8Bdc1VhYFxLCidr8awQoVu8uPXNbIWELe8qumwGJNKt2vzghByZZYmFTwuTyrgqder5KefVsc3BfagAwHL9Qs0V1FFLQVQ8_9lVqAsoHTsJHrFOniUsDwRr2bt6ZcY7j4nAYDyRaaQ6xK5iePZItfKsIxDCY2HzfT5hO3PyIg76kMFKlAokyFUqizfN-F89pvD39GdK2MvXCukrbz39ZnVJVbmgrAuyKAnlhoUsvU5VIDjxMIchGHMw_JmLpkyxciehFmj6deyia_VNXd3zai-Dh3hDlgP1wBeUwS-X_LYGUndf9JMjoDI-kXIfL5PVpi9vE6UABQ5BRnX61y8IHXBKeDHEy5_-rCkKNDa_q1a-FeMQxo8-KKjrllsobRoKEMBuvwsccZ-9e8zobj9X_BO41av8So55492Yl8e6pNsnjje7YTUUrQ; io=oseMnmapE4PMIaMOAAAg"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0"],"Accept":["application/json, text/plain, */*"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate"],"Connection":["keep-alive"],"Referer":["http://192.168.1.170:8081/printers"]}},"duration":0.008243361,"status":502,"err_id":"ud4iazvgw","err_trace":"reverseproxy.statusError (reverseproxy.go:886)

**Comment by Eidenz** [comment]
To add to this 502 error, it seems a log_path is missing as my docker logs are spammed with `stlib.go:30: log_path ./log does not exist` from the mmp_agent.

**Comment by kireol** [comment]
Yup.  I'm also getting this logpath issue.  

I tried creating a file and directory named log and it didn't stop the error.  

I did see somewhere that the logger was maybe be swapped out to a different library.

**Comment by EduardoOliveira** [comment]
Hi, I'm looking into it.
