### ISSUE TITLE
Feature Request: show models inside zip archives

### ISSUE THREAD

**Issue by Kimbaras** [Maker-Management-Platform/docs#29]
Hi there!

First of all, really cool project!

I've started playing with the project a couple of days ago, and I believe the main missing thing (at least from my side) is the ability to see the models inside a zip archive (or any other compressed file for what it matters).

Further details:

In the years I've grown quite a collections of STL (300+ GB) which where stored using Nextcloud (similar to what was briefly described in the last comment here #11 ).  Many of these files are inside an archive (from source, repacked be me, etc.) and seems there is no way to show what's inside.

I could upload pictures of the main file / printed object but it's not really the same (in my opinion at least)

Here the current behaviour I'm getting.
![Schermata 2024-03-01 alle 14 39 51](https://github.com/Maker-Management-Platform/docs/assets/102742484/c34eb1b2-7afe-4845-9c9b-062af39d47e8)

Beside this "nice to have", really cool project!

Thanks!

**Comment by EduardoOliveira** [comment]
Hi there,
You have the compressed projects due to storage limitations?
How do you see the interaction for that feature?

Looking at a possible implementation:
- You would have that compressed asset
- In the UI you would be able to "expand" the asset
- That would: 
  - Extract all the files within the asset into the current folder, flattening any folder structure inside the compressed asset
  or
  - Extract all the files to a temp folder, also flattening the structure. That temp folder would be deleted on demand or on a fixed timer
 
Thank you for your feedback

**Comment by Kimbaras** [comment]
Hey!

`You have the compressed projects due to storage limitations?`

Not really but that could also be a valid reason. 
In my specific case I'm keeping the zip / archives due to being the original form I downloaded them or because the project / model contains a lot of subpieces (eg: a truck model made by, let's say, 20 subpieces due to size or design).

Of the two proposed methods I like more the second options, to extract them to a temp folder and clear them after a while (I especially like the option to automatically deleted them after some time). 
Regarding the deletion on a fixed timer, I think it would be better to have as a default behaviour (let's say, delete the temp folder after 1 day) with the option to select a flag / checkbox to "protect" it and render it "delete on demand".

Thanks!

**Comment by EduardoOliveira** [comment]
This feature would be easier to implement if I would implement this one first
https://github.com/Maker-Management-Platform/mmp-ui/issues/127
Both are pretty distant from the current way things are done

**Comment by gentleAmateur** [comment]
This is similar to my biggest pain point with TagSpaces right now: I cannot view .7z contents. Personally the way I see it being done is the same way 7-Zip already does it (and can be run w/ that in the backend) is that it opens a temp folder and uses that in the GUI.

**Comment by EduardoOliveira** [comment]
@gentleAmateur this issue is being discussed here https://github.com/Maker-Management-Platform/docs/issues/30

**Comment by EduardoOliveira** [comment]
This feature is now fully implemented in the V2 branch, further discussion will be held here https://github.com/Maker-Management-Platform/agent/issues/136
